name: CI
on:
  pull_request:
  push:
    branches:
      - "master"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: rustup toolchain install stable --profile minimal

      - name: Install just
        uses: taiki-e/install-action@v2
        with:
          tool: just

      - run: just lint

  build:
    uses: ./.github/workflows/build.yml

  test:
    uses: ./.github/workflows/test.yml
