name: Test

on:
  workflow_call

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - run: rustup toolchain install stable --profile minimal

      - name: Install test tools
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest,just

      # cmd::build::build_implicit_pinned_and_unpinned is flaky under ubuntu
      - run: just test --retries 2
